default_install_hook_types: [commit-msg]
default_language_version:
    python: python3.9

repos:
  - repo: local
    hooks:
      - id: check-gitmoji-convention
        name: Check gitmoji convention
        always_run: true
        stages: [commit-msg]
        language: python
        entry: python -m buildtools.git_hooks.check_gitmoji

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
